[icons]
icons = "awesome5"

[icons.overrides]
cpu = "\uf2db"
memory_mem = "\uf538"
time = "\uf133"

[theme]
theme = "nord-dark"

[theme.overrides]
idle_fg = "#d8dee9"

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3,u:B,p:M) $cached $mem_total_used "

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "

[[block]]
block = "docker"
interval = 2
format = " $icon $running $total $images "

[[block]]
block = "net"
format = " $icon $graph_down "
interval = 1

[[block]]
block = "sound"
device_kind = "source"

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "taskwarrior"
interval = 60
format = " $icon $filter_name $count "
format_singular = " $icon    1 "
format_everything_done = " $icon    0 "
warning_threshold = 10
critical_threshold = 200

# Start Taskwarrior filters

[[block.filters]]
name = "ty"
filter = "+PENDING due:today"

[[block.filters]]
name = "tl"
filter = "+PENDING"

[[block.filters]]
name = "hi"
filter = "+PENDING priority:H"

[[block.filters]]
name = "md"
filter = "+PENDING priority:M"

[[block.filters]]
name = "lw"
filter = "+PENDING priority:L"

[[block.filters]]
name = "bl"
filter = "+backlog"

# End Taskwarrior filters

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%Y-W%V-%u %m-%d %H:%M') "

[[block]]
block = "battery"
interval = 10
format = "$percentage {$time |}"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "dnf"
interval = 1800
format = " $icon $count.eng(w:1) "
format_singular = " $icon "
format_up_to_date = " $icon "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
if_command = "test -f /usr/bin/dnf"
[[block.click]]
# shows dmenu with cached available updates. Any dmenu alternative should also work.
button = "left"
cmd = "dnf list -q --upgrades | tail -n +2"
update = true

[[block]]
block = "apt"
interval = 1800
format = " $icon $count "
format_singular = " $icon "
format_up_to_date = " $icon "
critical_updates_regex = "(linux|linux-lts|linux-zen)"
if_command = "test -f /usr/bin/apt"
[[block.click]]
# Updates the block on right click
button = "left"
update = true
