#!/usr/bin/env bash

# Force push after reset repository
# https://github.com/github/platform-samples/blob/master/pre-receive-hooks/force_push_restricted_branches.sh
zero_commit="0000000000000000000000000000000000000000"

function is_force_push() {
  # If this is a new branch there's no history to overwrite
  if [[ ${oldrev} == ${zero_commit} ]]; then
    return 1
  fi

  if git merge-base --is-ancestor ${oldrev} ${newrev}; then
    return 1
  else
    return 0
  fi
}

is_forced_push=$(is_force_push)

if [[ is_forced_push == 1 ]]; then
  echo "force push detected in restricted branch ${refname}"
  exit 1
fi


# Standard force push, to overwrite something
# Protected branches are the responsibility of the server
# https://gist.github.com/chales/13306eb261da13b5facd
PUSH_COMMAND=`ps -ocommand= -p $PPID`
FORCE_OPTION="delete|force|-f"

# if [[ "$CURRENT_BRANCH" =~ $PROTECTED_BRANCHES && "$PUSH_COMMAND" =~ $FORCE_OPTION ]]; then
if [[ "$PUSH_COMMAND" =~ $FORCE_OPTION ]]; then
  echo "Prevented force-push to protected branch '$CURRENT_BRANCH'!"
  echo "You should only Force Push to protected branches if you fully understand the effect."
  exit 1
fi

exit 0
