name: Daily check update assets

on:

  schedule:
    - cron:  '01 00 * * *'

  workflow_dispatch:

jobs:
  updates:
    runs-on: ubuntu-latest
    env:
      PREFIX_TEST: test_

    steps:

      - name: checkout repo
        uses: actions/checkout@v5

      - run: make update

      - name: Diff install scripts 
        run: make test-diff-install-script

      - name: Diff themes
        run: make test-diff-themes
